// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_create_entry_session from "./routes/api/create-entry-session.ts";
import * as $api_join from "./routes/api/join.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_verify_entry_session from "./routes/api/verify-entry-session.ts";
import * as $index from "./routes/index.tsx";
import * as $themes from "./routes/themes.tsx";
import * as $auth_account_box from "./islands/auth/account-box.tsx";
import * as $auth_join from "./islands/auth/join.tsx";
import * as $auth_login from "./islands/auth/login.tsx";
import * as $auth_modal from "./islands/auth/modal.tsx";
import * as $layout_profile from "./islands/layout/profile.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/create-entry-session.ts": $api_create_entry_session,
    "./routes/api/join.ts": $api_join,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/verify-entry-session.ts": $api_verify_entry_session,
    "./routes/index.tsx": $index,
    "./routes/themes.tsx": $themes,
  },
  islands: {
    "./islands/auth/account-box.tsx": $auth_account_box,
    "./islands/auth/join.tsx": $auth_join,
    "./islands/auth/login.tsx": $auth_login,
    "./islands/auth/modal.tsx": $auth_modal,
    "./islands/layout/profile.tsx": $layout_profile,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
