// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $themes from "./routes/themes.tsx";
import * as $layout_profile from "./islands/layout/profile.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/themes.tsx": $themes,
  },
  islands: {
    "./islands/layout/profile.tsx": $layout_profile,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
